services:
  app:
    container_name: go-app-sensors
    build:
      context: .
      dockerfile: Dockerfile
      target: dev # ← ini yang memilih stage "dev"
      args:
        GO_VERSION: "1.25"
    image: go-app-sensors:latest
    working_dir: /src
    volumes:
      - .:/src
      - go-cache:/go/pkg/mod
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["go", "run", "./cmd/app"] # jalankan langsung Go tanpa air

volumes:
  go-cache:
